lo_l_api:
    resource: "@LoLApiBundle/Controller/"
    type:     annotation
    prefix:   /lolapi

brawl:
    resource: "@BrawlBundle/Controller/"
    type:     annotation
    prefix:   /brawl

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
