# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
#updated for fosuser
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
                    id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            oauth:
                failure_path: /en/connect
                login_path: /en/connect
                check_path: /en/connect
                default_target_path: /
                provider: fos_userbundle
                resource_owners:
                    facebook: "/login/check-facebook"
                    google: "/login/check-google"
                oauth_user_provider:
                    service: cmb.user.provider.fosub_bridge

            form_login:
                provider: fos_userbundle
                check_path: /login_check
                login_path: /login
                default_target_path: /

            anonymous: true
            logout:
                path: /logout
                target: / #where to go after logout


    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z]+/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z]+/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z]+/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z]+/admin/, role: ROLE_ADMIN }
        - { path: ^/[a-z]+/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z]+/, roles: ROLE_USER }