<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChampionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampionMasteryRepository extends EntityRepository
{
    public function findBySummonerAndChampionId($summoner, $championId)
    {
        $query = $this->createQueryBuilder('cm')
            ->where('cm.summoner = :summoner')->andWhere('cm.championId = :championId')
            ->setParameter('summoner', $summoner)
            ->setParameter('championId', $championId)
            ->getQuery();
        return $query->getOneOrNullResult();
    }
}
