<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StaticChampionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaticChampionRepository extends EntityRepository
{
    public function findByChampionIdsWithIndex($array)
    {
        $query = $this->createQueryBuilder('sm')
            ->indexBy('sm','sm.championId' )
            ->where('sm.championId IN (:championIds)')
            ->setParameter('championIds', $array)
            ->getQuery();
        return $query->getResult();
    }
}
